import { NextRequest, NextResponse } from "next/server";

/**
 * Pure Dynamic Web Image Search API Route
 * Searches live web image engines on-the-fly for any recipe generated by Gemini without hardcoded lists.
 */
export async function GET(req: NextRequest) {
  try {
    const { searchParams } = new URL(req.url);
    const query = (searchParams.get("q") || "").trim();

    if (!query) {
      return NextResponse.json({ success: false, message: "Query parameter 'q' diperlukan" }, { status: 400 });
    }

    const searchQuery = `${query} masakan indonesia makanan`;

    // 1. Coba Google Custom Search API jika Key & CX tersedia di .env
    const googleKey = process.env.GOOGLE_SEARCH_API_KEY || process.env.GEMINI_API_KEY;
    const googleCx = process.env.GOOGLE_SEARCH_CX;

    if (googleKey && googleCx) {
      try {
        const googleEndpoint = `https://www.googleapis.com/customsearch/v1?q=${encodeURIComponent(searchQuery)}&searchType=image&num=1&key=${googleKey}&cx=${googleCx}`;
        const gRes = await fetch(googleEndpoint, { next: { revalidate: 3600 } });
        if (gRes.ok) {
          const gData = await gRes.json();
          if (gData.items && gData.items.length > 0 && gData.items[0].link) {
            return NextResponse.json({
              success: true,
              engine: "GOOGLE_SEARCH_IMAGE_LIVE",
              imageUrl: gData.items[0].link,
              title: gData.items[0].title || query,
            });
          }
        }
      } catch (gErr) {
        console.warn("Google live search error:", gErr);
      }
    }

    // 2. Live Dynamic Wikimedia Commons Media Search API (Free Global Live Image Engine)
    try {
      const wikiSearchUrl = `https://commons.wikimedia.org/w/api.php?action=query&generator=search&gsrsearch=${encodeURIComponent(query)}&gsrlimit=1&prop=imageinfo&iiprop=url&format=json&origin=*`;
      const wikiRes = await fetch(wikiSearchUrl, { next: { revalidate: 3600 } });
      if (wikiRes.ok) {
        const wikiData = await wikiRes.json();
        const pages = wikiData.query?.pages;
        if (pages) {
          const firstKey = Object.keys(pages)[0];
          const fileUrl = pages[firstKey]?.imageinfo?.[0]?.url;
          if (fileUrl) {
            return NextResponse.json({
              success: true,
              engine: "WIKIMEDIA_COMMONS_DYNAMIC_SEARCH",
              imageUrl: fileUrl,
              title: query,
            });
          }
        }
      }
    } catch (wErr) {
      console.warn("Wikimedia dynamic search error:", wErr);
    }

    // 3. Live Web Culinary Search Endpoint
    const duckSearchUrl = `https://api.duckduckgo.com/?q=${encodeURIComponent(query)}&format=json`;
    try {
      const ddgRes = await fetch(duckSearchUrl, { next: { revalidate: 3600 } });
      if (ddgRes.ok) {
        const ddgData = await ddgRes.json();
        if (ddgData.Image) {
          return NextResponse.json({
            success: true,
            engine: "DUCKDUCKGO_LIVE_SEARCH",
            imageUrl: ddgData.Image,
            title: query,
          });
        }
      }
    } catch (dErr) {
      console.warn("DDG search error:", dErr);
    }

    // 4. Pure Dynamic Foodish Real Photography Endpoint (Randomized Authentic Live Real Food Image)
    const foodishRes = await fetch("https://foodish-api.com/api", { next: { revalidate: 60 } });
    if (foodishRes.ok) {
      const fData = await foodishRes.json();
      if (fData.image) {
        return NextResponse.json({
          success: true,
          engine: "FOODISH_REAL_CULINARY_LIVE",
          imageUrl: fData.image,
          title: query,
        });
      }
    }

    return NextResponse.json({
      success: false,
      message: "Tidak ada gambar ditemukan dari live search",
    }, { status: 404 });
  } catch (error: any) {
    return NextResponse.json({
      success: false,
      error: error.message || "Internal live search error",
    }, { status: 500 });
  }
}
